server:
  port: 9000

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  web:
    resources:
      static-locations: /WEB-INF/static
  h2:
    console:
      enabled: true
  datasource:
     url: jdbc:h2:mem:testdb
